image: docker:19.03.1
stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  DOCKER_DRIVER: overlay2


before_script:
  - cd reddit


build_job:
  services:
    - docker:19.03.1-dind

  stage: build
  # image: docker:19.03
  # # services:
  # #   - docker:19.03-dind
  ##

  tags:
    - reddit


  script:
    - docker info
    - docker build -t reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID .
    - docker tag reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID volkmydj/gitlab-reddit:$CI_PIPELINE_IID
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
    - docker push volkmydj/gitlab-reddit:$CI_PIPELINE_IID

    - docker images

test_unit_job:
  image: ruby:2.4.2
  stage: test
  services:
    - mongo:latest
  script:
    - bundle install
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
