image: ruby:2.4.2
stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  # - bundle install


build_job:
  image: docker:19.03
  # variables:
  #   # DOCKER_HOST: tcp://docker:2375/
  #   DOCKER_DRIVER: overlay2
  #   DOCKER_TLS_CERTDIR: "/certs"
  # services:
  #   - docker:19.03-dind

  stage: build
  # image: docker:19.03
  # # services:
  # #   - docker:19.03-dind

  # tags:
  #   - test


  script:
    - docker info
    - docker build -t reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID .
    # - docker build -t reddit:latest .
    - docker images

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - bundle install
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
