global:
    slack_api_url: 'https://hooks.slack.com/services/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'
route:
  receiver: 'slack-notifications'
  
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#prometheus'

- name: 'email-me'
  email_configs:
    - to:  prometheus@gmail.com
      from: alert@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: alert@gmail.com
      auth_identity: alert@gmail.com
      auth_password: 123qweasd
