version: '3.3'
services:
  post_db:
    container_name: post_db
    image: ${DB_IMAGE}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ../src/ui/
    container_name: ui
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORTS}
    networks:
      - front_net
    
  post:
    build: ../src/post-py/
    container_name: post
    image: ${USER_NAME}/post
    networks:
      front_net:
        aliases:
          - post
          - comment
      back_net:
        aliases:
          - post
          - comment
    ports:
      - '5000:5000'
  comment:
    build: ../src/comment/
    container_name: comment
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
           - comment

volumes:
  post_db:

networks:
  ront_net:
  back_net: