version: '3.5'
services:
  post_db:
    container_name: post_db
    image: ${DB_IMAGE}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    container_name: ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${UI_PORTS}
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    container_name: post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
        aliases:
          - post
          - comment
      back_net:
        aliases:
          - post
          - comment
    ports:
      - '5000:5000'
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    container_name: comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  front_net:
    name: front_net
  back_net:
    name: back_net
