version: '3.3'
services:
  post_db:
    container_name: post-db
    image: ${DB_IMAGE}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ../src/ui/
    container_name: ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORTS}
    networks:
      - front_net
  post:
    build: ../src/post-py/
    container_name: post
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
  comment:
    build: ../src/comment/
    container_name: comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
           - comment

  prometheus:
    build: ../monitoring/prometheus
    image: ${USERNAME}/prometheus:${PROM_VERSION}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net

  mongo_exporter:
    build: ../monitoring/mongodb_exporter
    container_name: mongo-exporter
    image: ${USERNAME}/mongodb_exporter:${MDB_EXPORTER_VERSION}
    networks:
      back_net:
        aliases: 
          - mongo-exporter

  blackbox_exporter:
    build: ../monitoring/blackbox_exporter
    image: ${USERNAME}/blackbox-exporter:${BLACKBOX_VERSION}
    container_name: blackbox-exporter
    networks:
      back_net:
        aliases:
          - blackbox-exporter
      front_net:
        aliases:
          - blackbox-exporter


    



volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    external: false
  front_net:
    external: false
