---
    apiVersion: apps/v1beta2
    kind: Deployment
    metadata:
      name: post-db-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: post-db
      template:
        metadata:
          name: post-db
          labels:
            app: post-db
        spec:
          containers:
          - image: mongo
            name: post-db
