apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
- name: InfluxDB
  type: influxdb
  acces: proxy
  database: telegraf
  user: telegraf
  password: telegraf
  url: http://influxdb:8086
  jsonData:
    httpMode: GET

- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://trickster:9089
  password:
  user:
  database:
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
    graphiteversion: "1.1"
    tlsAuth: false
    tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true
