---
version: '3.3'
services:
  ui:
    volumes:
      - app_ui:/app
    command: puma --debug -w 2

  post:
    volumes:
      - app_post:/app

  comment:
    volumes:
      - app_comment:/app
    command: puma --debug -w 2


volumes:
  app_ui:
  app_post:
  app_comment:
